### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by hhzl** [hhzl/Amber-snapsvg-demo#1]
Please add notes, remarks about the [code](https://github.com/hhzl/Amber-snapsvg-demo) and the [process](https://github.com/hhzl/Amber-snapsvg-demo/blob/master/README.md).

**Comment by ghost** [comment]
If snap.svg library is AMD-aware (so if has some header doing define call), it likely exports the Snap object. So it should not be accessed via global, like:

``` st
| s bigCircle smallCircle |

s := Snap value: 300 value: 600.
```

but via loader, like:

``` st
| s snapLib bigCircle smallCircle |

snapLib := require value: 'snap.svg'.
s := snapLib value: 300 value: 600.
```

**Comment by herby** [comment]
In that case, it needs not to be added to `deploy.js

**Comment by ghost** [comment]
You can even load it dynamically completely, not putting it to `deploy.js` but actually loading it jit, like:

``` st
| s bigCircle smallCircle |

require value: #('snap.svg') value: [ :snapLib |
  s := snapLib value: 300 value: 600.
```

but the previous seems easier to read.

**Comment by hhzl** [comment]
@herby 

## 1

regarding the first comment: thank you, updated to use

```
| s snapLib bigCircle smallCircle |

snapLib := require value: 'snap.svg'.
s := snapLib value: 300 value: 600.
```

[code](https://github.com/hhzl/Amber-snapsvg-demo/blob/master/src/AmberSnapsvg.st)

## 2

Regarding the second comment: 

an argument in favor of adding it to `deploy.js` is that the library is included in the file  `the.js` to be used for deployment.

**Comment by ghost** [comment]
Hannes Hirzel wrote:

> @herby https://github.com/herby
> 
> ```
> 1
> ```
> 
> regarding the first comment: thank you, updated to use
> 
> || s snapLib bigCircle smallCircle |
> 
> snapLib := require value: 'snap.svg'.
> s := snapLib value: 300 value: 600.
> |
> 
> code 
> https://github.com/hhzl/Amber-snapsvg-demo/blob/master/src/AmberSnapsvg.st
> 
> ```
> 2
> ```
> 
> Regarding the second comment:
> 
> an argument in favor of adding it to |deploy.js| is that the library 
> is included in the file |the.js| to be used for deployment.

Oh yes, I forgot. Definitely.

**Comment by hhzl** [comment]
Thank you
