### ISSUE TITLE
Installation no longer works in Amber v0.14.3

### ISSUE THREAD

**Issue by hhzl** [hhzl/Amber-snapsvg-demo#3]
The code in this repo works fine for Amber v0.14.1

However if I do

```
git clone https://github.com/hhzl/Amber-snapsvg-demo.git
cd Amber-snapsvg-demo
npm install
bower install
grunt devel
```

no longer works. 

**Reason**

A newer version of Amber is loaded. This probably causes the problem.

**Comment by hhzl** [comment]
If `bower.json` is adapted

```
  "dependencies": {
    "amber": "0.14.1",
    "snap.svg": "~0.3.0"
  },
  "devDependencies": {
    "amber-ide-starter-dialog": "^0.1.0",
    "amber-attic": "^0.1.0",
    "helios": "0.3.0"
  }
```

then is works fine

```
    "amber": "^0.14.1",
```

was replaced with 

```
    "amber": "0.14.1",
```

and

```
           "^helios": "0.3.0"
```

was replaced with

```
          "helios": "0.3.0"
```

**No [caret](http://en.wikipedia.org/wiki/Caret)**, so version number if fixed.

**Comment by ghost** [comment]
You are doing strange things here. Better than taking caret out is update thing to work with 0.14.3. Could you say what in 0.14.3 made it not to work?

**Comment by hhzl** [comment]
I cannot say at the moment what maked 0.14.3 not to work. I'll investigate it.

@I agree that taking the caret out is not a good thing long term.
I take it out at the moment for testing purposes find out where the problem is, i.e. which version changes the problem.

I.e. what is the latest combinations of versions which still works and which version does break it.

See also https://github.com/amber-smalltalk/helios/issues/50. I'd like to know if that has an influence. Maybe not.

**Comment by hhzl** [comment]
## Retest

`bower.json`  still has `^0.14.1` for Amber

```
git clone https://github.com/hhzl/Amber-snapsvg-demo.git
cd Amber-snapsvg-demo
npm install
bower install
grunt devel
amber serve
```

**Result** successful.
![amber-snap svg-test-with-0 14 3_from 2015-01-27 13 57 08](https://cloud.githubusercontent.com/assets/1112023/5919529/7da2f23e-a62c-11e4-9e59-d5a3e45a81ad.png)

Installed was

```
~/Amber-snapsvg-demo/bower_components/amber $ cat bower.json

{
   "name": "amber",
   "version": "0.14.3",
   "main": "support/amber.js",
```

**Comment by ghost** [comment]
Nice! Now hopefully the rest will work as well (adding imports, removing from deploy.js, updating README).
